/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import datos.DAOSillas;
import entidades.Silla;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import entidades.Factura;
/**
 *
 * @author Kevin
 */
public class JFrameReserva extends javax.swing.JFrame {

    private List<Silla> listaSillas; // Lista completa de sillas
    private DefaultTableModel modeloSillasDisponibles; //Tabla con los datos de las sillas disponibles
    private DefaultTableModel modeloSillasReservables; //Tabla con los datos de las sillas que se encuentran para reservar
    private String login;
    /**
     * Creates new form Reserva
     */
    public JFrameReserva(String login) {
        this.login = login;
        
        setTitle("Reservar sillas");
        //Centrar
        initComponents();
        cargarTramos(); //Cargamos los nombres de los tramos en el comboBox
        cargarSillas();
        filtroPorTramo();
        this.setLocationRelativeTo(null);
    }

    //Método para cargar las sillas
    private void cargarSillas(){
        DAOSillas daoSillas = new DAOSillas();
        listaSillas = daoSillas.consultarSillasSinReserva(); 
        
        actualizarTabla(listaSillas);
    }
    
    //Método para cargar los datos de la consulta tramos
    private void cargarTramos(){
        DAOSillas daoSillas = new DAOSillas();
        List<String> tramos = daoSillas.consultarTramos();
        
        //Limpiamos la lista para que no se acumule
        tramoComboBox.removeAllItems();
        
        //Nombres de los tramos
        tramoComboBox.addItem("Todos"); // Así podemos volver a ver todas las sillas disponibles
        for (String tramo : tramos) {
            tramoComboBox.addItem(tramo);
        }
    }
    
    private void filtroPorTramo() {
        tramoComboBox.addActionListener(e -> {
            String tramoSeleccionado = (String) tramoComboBox.getSelectedItem();
            // Filtrar la lista de sillas según el tramo seleccionado
            List<Silla> sillasFiltradas;
            if ("Todos".equals(tramoSeleccionado)) {
                sillasFiltradas = listaSillas; // Mostrar todas las sillas
            } else {
                sillasFiltradas = listaSillas.stream() //Aplicamos stream para filtrar las sillas
                        .filter(silla -> silla.getTramo().equals(tramoSeleccionado))
                        .collect(Collectors.toList()); //Ordenamiento por defecto (alfabético)
            }

            // Actualizar la tabla con las sillas filtradas
            actualizarTabla(sillasFiltradas);
        });
    }
    
    private void actualizarTabla(List<Silla> sillas) {
        modeloSillasDisponibles = (DefaultTableModel) tablaSillasDisponibles.getModel(); //Casteamos la table porque no es compatible
        modeloSillasDisponibles.setRowCount(0); // Aquí limpiamos la tabla

        for (Silla silla : sillas) {
            modeloSillasDisponibles.addRow(new Object[] { silla.getNumero(), silla.getTramo(), silla.getPrecio() });
        }
    }
    
    private void actualizarPrecioTotal() {
        double precioTotal = 0.0;

        // Iterar sobre las filas de la tabla listaReservables y sumar los precios
        for (int i = 0; i < modeloSillasReservables.getRowCount(); i++) {
            // Obtener el valor de la columna "Precio" para cada fila (columna 2)
            precioTotal += (double) modeloSillasReservables.getValueAt(i, 2);
        }

        // Actualizar la etiqueta con el precio total formateado
        campoPrecioTotal.setText(String.format("%.2f €", precioTotal));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSillasDisponibles = new javax.swing.JTable();
        botonReservar = new javax.swing.JButton();
        etiquetaSillasDisponibles = new javax.swing.JLabel();
        tramoComboBox = new javax.swing.JComboBox<>();
        botonAgregar = new javax.swing.JButton();
        botonQuitar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaReservables = new javax.swing.JTable();
        toggleOrdenPrecio = new javax.swing.JToggleButton();
        etiquetaTotal = new javax.swing.JLabel();
        campoPrecioTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaSillasDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Número", "Tramo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSillasDisponibles.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaSillasDisponibles);
        if (tablaSillasDisponibles.getColumnModel().getColumnCount() > 0) {
            tablaSillasDisponibles.getColumnModel().getColumn(0).setPreferredWidth(5);
            tablaSillasDisponibles.getColumnModel().getColumn(1).setPreferredWidth(140);
            tablaSillasDisponibles.getColumnModel().getColumn(2).setPreferredWidth(5);
        }

        botonReservar.setText("Reservar");
        botonReservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonReservarMouseClicked(evt);
            }
        });

        etiquetaSillasDisponibles.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        etiquetaSillasDisponibles.setText("Reservar Sillas");

        tramoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonAgregar.setText("Agregar");
        botonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAgregarMouseClicked(evt);
            }
        });
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonQuitar.setText("Quitar");
        botonQuitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonQuitarMouseClicked(evt);
            }
        });
        botonQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuitarActionPerformed(evt);
            }
        });

        tablaReservables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Tramo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaReservables);

        toggleOrdenPrecio.setText("Ordenar por Precio");
        toggleOrdenPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleOrdenPrecioActionPerformed(evt);
            }
        });

        etiquetaTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiquetaTotal.setText("TOTAL:");

        campoPrecioTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoPrecioTotal.setText("0 €");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(toggleOrdenPrecio)
                        .addContainerGap(727, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonQuitar, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tramoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 176, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(botonReservar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etiquetaTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoPrecioTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaSillasDisponibles)
                .addGap(291, 291, 291))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(etiquetaSillasDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleOrdenPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tramoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonReservar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonQuitar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaTotal)
                    .addComponent(campoPrecioTotal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonQuitarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAgregarMouseClicked
        int selectedRow = tablaSillasDisponibles.getSelectedRow(); // Obtener fila seleccionada en listaSillasDisponibles
        if (selectedRow != -1) { // Asegurarse de que se seleccionó una fila
            // Obtener los datos de la fila seleccionada
            Object numero = tablaSillasDisponibles.getValueAt(selectedRow, 0);
            Object tramo = tablaSillasDisponibles.getValueAt(selectedRow, 1);
            Object precio = tablaSillasDisponibles.getValueAt(selectedRow, 2);

            // Agregar la fila seleccionada a listaReservables
            modeloSillasReservables = (DefaultTableModel) tablaReservables.getModel();
            modeloSillasReservables.addRow(new Object[] { numero, tramo, precio });

            // Eliminar la fila seleccionada de listaSillasDisponibles
            DefaultTableModel modeloDisponibles = (DefaultTableModel) tablaSillasDisponibles.getModel();
            modeloDisponibles.removeRow(selectedRow);
            
            //Actualizar precio total
            actualizarPrecioTotal();
        }
    }//GEN-LAST:event_botonAgregarMouseClicked

    private void botonQuitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonQuitarMouseClicked
        int selectedRow = tablaReservables.getSelectedRow(); // Seleccionar una fila
        if (selectedRow != -1) { // Fila seleccionada
            // Obtener los datos de esta fila
            Object numero = tablaReservables.getValueAt(selectedRow, 0);
            Object tramo = tablaReservables.getValueAt(selectedRow, 1);
            Object precio = tablaReservables.getValueAt(selectedRow, 2);

            // Agregamos la silla en listaSillasDisponibles
            modeloSillasDisponibles = (DefaultTableModel) tablaSillasDisponibles.getModel();
            modeloSillasDisponibles.addRow(new Object[] { numero, tramo, precio });

            // Eliminamos la silla de listaReservables
            modeloSillasReservables = (DefaultTableModel) tablaReservables.getModel();
            modeloSillasReservables.removeRow(selectedRow);
            
            //Actualizar precio total
            actualizarPrecioTotal();
        }
    }//GEN-LAST:event_botonQuitarMouseClicked

    private void botonReservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonReservarMouseClicked
        if (tablaReservables.getRowCount()== 0) {
        JOptionPane.showMessageDialog(this,
                "No hay sillas seleccionadas para reservar.",
                "Advertencia",
                JOptionPane.WARNING_MESSAGE);
            return; 
        }
        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Quieres confirmar la reserva?",
                "Confirmar Reserva",
                JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            generarFicheroFactura(login, , );
        }
    }//GEN-LAST:event_botonReservarMouseClicked

    private void toggleOrdenPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleOrdenPrecioActionPerformed
        if (toggleOrdenPrecio.isSelected()) {
              // Ordenar por precio descendente
            listaSillas.sort((s1, s2) -> s1.compareToDesc(s2));
        } else {
            // Ordenar por precio ascendente
            listaSillas.sort((s1, s2) -> s1.compareTo(s2));
        }
        actualizarTabla(listaSillas);
    }//GEN-LAST:event_toggleOrdenPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonQuitar;
    private javax.swing.JButton botonReservar;
    private javax.swing.JLabel campoPrecioTotal;
    private javax.swing.JLabel etiquetaSillasDisponibles;
    private javax.swing.JLabel etiquetaTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaReservables;
    private javax.swing.JTable tablaSillasDisponibles;
    private javax.swing.JToggleButton toggleOrdenPrecio;
    private javax.swing.JComboBox<String> tramoComboBox;
    // End of variables declaration//GEN-END:variables
}
